<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.60.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.60.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\SmartMail.Application\SmartMail.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\SmartMail.Infrastructure\SmartMail.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\SmartMail.Persistence\SmartMail.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\smartmail.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\emailcampaign.proto" GrpcServices="Server" />
  </ItemGroup>

</Project>
